### ISSUE TITLE
Plugin start error in ArenaManager

### ISSUE THREAD

**Issue by Lucki2g** [pogostick29dev/Bloodbath#5]
When running the plugin for the first time it comes up with this error:

java.lang.ExceptionInInitializerError
at me.pogostick29dev.com.ArenaManager.setup<ArenaManager.java:24> ~[?:?]
at me.pogostick29dev.com.Main.onEnable<Main.java:29> ~[?:?]

At that line it says: 
for (String arenaID : SettingsManager.getArenas().getKeys()) {

Could it be because no arena has been set yet?

**Comment by matthijs2704** [comment]
Can you post the complete exception in a pastebin please?

**Comment by Lucki2g** [comment]
Right there:
http://pastebin.com/ym3nP9wd

**Comment by matthijs2704** [comment]
Have you renamed the plugin (in plugin.yml)?

**Comment by Lucki2g** [comment]
No

**Comment by matthijs2704** [comment]
So it's fresh from the git without any modifications?

**Comment by matthijs2704** [comment]
Seems to be the same as #3

**Comment by Lucki2g** [comment]
Oh i see! I'll check it out ;) thx

**Comment by matthijs2704** [comment]
Sure :)

**Comment by Lucki2g** [comment]
Thanks! figured it out :)

Also! this doesn't work for all versions of minecraft:
gui = Bukkit.getServer().createInventory(null, InventoryType.CHEST, ChatColor.GOLD + "Kit Selector");

You'll have to change the InventoryType.CHEST to an int which can be divided by 9 so (9, 18, 27... etc)
Just a hint, because it didn't work for me but I knew ;P

**Comment by matthijs2704** [comment]
You don't have to... InventoryType.CHEST equals an inventory of size 9 (in bukkit code ;))

**Comment by Lucki2g** [comment]
idk why it then didn't work before i did:
createInventory(null, 27, ChatColor.GOLD + "Kit Selector");

maybe my craftbukkit is weird...

**Comment by theAnthrax** [comment]
//Sorry for posting on such an old thread but if someone still needs this.

public static Plugin getPlugin() {
        return Bukkit.getServer().getPluginManager().getPlugin("Bloodbath");
    }

replace "Bloodbath" with whatever you called your plugin in plugin.yml.
